# Postgres
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_URL'] || 'localhost' %>
  pool: 5

prod-default: &prod-default
  adapter: postgresql
  encoding: utf8
  min_messages: WARNING
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  username: artik
  database: artik-dev

test:
  <<: *default
  username: artik
  database: artik-test

production:
  <<: *prod-default
  database: artik-prod
